import bentoml


def predict(bento_model, testdata):
    """
    Executes model inference inside the containerised BentoML deployment environment.

    This function serves as the core execution entrypoint when the service is
    deployed. It retrieves the registered model from the BentoML Model Store,
    processes incoming live test data payloads, and returns the model's
    predictions.

    Parameters
    ----------
    bento_model : bentoml.Model
        The retrieved model reference packaged within the Bento container.
    testdata : Any
        The incoming inference payload (e.g., Dataframe, Tensor, or JSON dict).

    Returns
    -------
    Any
        The raw prediction results generated by the model.
    """

    prediction = bento_model.predict(testdata)
    return prediction


class BentoModel:
    def __init__(self):
        self.model_name = None

    def __init(self):
        self.model_name = None

    def import_model(self, name:str, model_uri:str):
        model = bentoml.mlflow.import_model(name, model_uri)
        self.model_name = ":".join([model.tag.name, model.tag.version])
        return self.model_name

    def load_model(self, model_name=None):
        if model_name is None:
            model_name = self.model_name
        bento_model = bentoml.mlflow.load_model(model_name)
        return bento_model

    def get_model(self, model_name=None):
        if model_name is None:
            model_name = self.model_name
        bento_model = bentoml.models.get(model_name)
        runner = bento_model.to_runner()
        runner.init_local()
        return runner
    