name: MLOps CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 #Use updated version instead

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r setup/requirements.txt
        pip install pkg-resources-backport

    - name: Patch Deepchecks for NumPy 2.x compatibility
      run: |
        # Dynamically locate the file within your environment and fix np.Inf
        DEEPCHECKS_FILE=$(python -c "import deepchecks.tabular.checks.model_evaluation.performance_bias as m; print(m.__file__)")
        sed -i 's/np.Inf/np.inf/g' "$DEEPCHECKS_FILE"

    - name: Run Model Validation (Deepchecks) # Could use Evidently AI, Great Expectations or DeepChecks
      run: python ci_cd/validation.py
    
    - name: Upload Deepchecks Report to GitHub Pages
      if: always()
      run: |
        mkdir -p gh-pages
        mv deepchecks_report.html gh-pages/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages

    - name: Train model
      run: |  
        python ci_cd/train.py

    - name: Save the trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model/house_regression_model.pkl
         